---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: indexer-cred
  namespace: wazuh
spec:
  encryptedData:
    password: AgChB75tG8WbwUbyvO9oWYuKWApeLpP9cwaZZGDplwR+5d6SsG2fTiG/kr2uW9nvqXKlsyzT2Tv+Me3b4INdonZcCfvJ3Qs4IwpjyhRw3O4H8x3I6jnXR4NqGKMZqbbkUOG5fdjkP0ZatlYcmmEEBhFChGhZq78EX2SwEIixk4+YyLComyeG1MFgcvPuGkDWnGUT9cmfzc5JKQDksN7+1Ip5dx11KnFby7Fs3DwVV14AOKxnfBWmmp9f5NG9ozsFf2OsGxNX1pmdL58D049vA15NSVJkrEVUQgX4l8R6bwdXgsejAChEt+ELJQUxu5tqc4P/twX3LX6wd1RsdOuIx9KXnEDYZH/99UxdTOkCIixi4n/NrXTtXFBTeKreXt+tD4Pewm4dChy+kdmyChfj2xBqVCAQfvhGcIXjwWPHW6ZdR1TYzprAbu6G3n3ijDEN7MJR/2dqmu1k5YTXS70NXnRgABaCIwbZ4/8519AMWVMmFP2dqpnIwQwWefli+QDQYYITLgg0K1bCq1+sjyRVhpjoEw0M2r8VjNUmmeHcAt2cpYJE4Gip2p/gy7BtXUZVEPjr0SwQd3tAZL5eaWBaF623pFr2/TziZLsRj34S4NvAEBhZMeIrppuE3gjaFuylJKfioFCGKiKe4emBtjzWtCbQbQwERGTVZSRp4NPPBzQWqCQVfnNtuqWReAKhrwo+AowExdJWf7UAGUb0BikbR5QyDbVCMwL1c4BYwzF8O1hMMvEHkYutmCZJkcSuBOfv8Ag=
    username: AgCRP1eaUh2LGhkfiE2g0iTKhFT2UjIIhE1QchdKEhdA/UMwK0QTc4rhfrIOCArg13iyqCqZZGmS8KGxMrlmzcYNbqu7BsPNoJovec8SK3NPAien5H2eYDMly0yBXoeXmUhnFVt9NKGCL2coxYWHwWxH4BSWxBkdPTzQohaTv2avma/GUSJhkmJ9t/al+3nty/G/UohvIKB9zyws+M92tWFUa0bxV535kKH1e+Wg4qxv5F0RSWzR8SNayKHKXbXj9uT1pkvTy+me1EKI4OVTZnYAxhbxsYFPpm1eUuirkkqAO5tuYyZ18JTaws/RAW/tIwh2Hu9R4oaE7x8y/Qfn693f3tTfEa3thoMfsEzxuZw7GkJjTEKHm7RK2CYyVLgYoFK1Fby4wb27tRjYPBXYMGFPhRDqMO98mhoVQkHLjzG2AgwYjl+yLJQQJ4g8ZL4eZ+QD2rzioHfpjGTFmVsBP4qjY1PYl+rBU01x2kOaW/Pu9RYinzemdyn0pTRuQYcJG3bw+fHGmTIhczzQKscPjUITO9U06kcRZ3ZJGsz7H8nJIsUWe9jre1x2bvl4W+hVtoD0OSnIIOhe9h3tw7zj61CoC5KPOiMFhGiSNT0b7rssa3aoA8oVR5osCNH8wKyL9pEUksaQgEqUfOizcIHmHRFEg/veilb53kC3mrpMQ5iiorDPhyCmvdZxFA73OdzNf8c7ZypjaQ==
  template:
    metadata:
      name: indexer-cred
      namespace: wazuh
