---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-authd-pass
  namespace: wazuh
spec:
  encryptedData:
    authd.pass: AgAY+pRSsPg9DbWWb8EfMrmp1AYxyaXbG8hxq2QWqFH0BbqZJ9JAJO4zzR39+5YQf+MGd9YBm8Zq0Dn1u21MDFTSbL7AUELkQZLWG0rUKNh9IHnJycBtaWWGXBfHQsmobwVQG5lv/Mrh112tQPBtXRvw6kPU1gnRt1/HDobmcPn5G9FEIJxWFhVLXLS48UlUs+ihEUJS5vcEqClWI5qnuaBHAgs0bxu43HBO9a7X3FahrSpAQ/xvhzjBL/ScSQLuU/p4alVexDPYRXrWNUYpuKc2IFKPyh7n+KKpBY2ysivdKXvbEnS0+ZqmnQpl2JMPPicRGQ78rwFuZV1hf9GCScQgvVkngGzYduQDIn5l0GsnQx7YDem9TPV5lJlT84sJ0uHVA+/SnyoeA1XQrm/YksF6IIj48K+nupXQIvwv2wpdYC5Kn1uRCbEhN9jMK4saOgSLKFzqdObj4QjDUXp0Mvyqnks13qpA8VKJ57oxDPhkVZLPwGBpreHwHnqH4kZypRgd5hXH+QHxe9LGJOTkYhzLX4BaDixZAnYEEalcyVAY5m+ciQ3SGVU/TKM/EEtkDic9dfavAUwFhIQwPPL90SnQIaCZ+UnX8APw97qKArOFHAhANo7sIVQEd2AEFXoY7TnWtbCP8Tn5zegQOtEYvTXsTdUfqUFHZzuW7LvMuir2Doe/bzRXNIyhSWkKUOpJtvr9bn+nBoB+qeCoyBMp87cmc5JvMmBh6u+aiZWMGoV5a4jkm+5+r7az8SXyeiQmexM=
  template:
    metadata:
      name: wazuh-authd-pass
      namespace: wazuh
