---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
spec:
  encryptedData:
    password: AgA8cgRsYIZV7qOYvuIR0tAtA2vb0DgaziBTKsaxApdFpEgRxvvymWIMaeyEzjAYkpoEBHVy8rnlVa9SrHoXHgAAAamhFf3zet4Z1ctA6Z/RPcjBm8AX0eZ5ihMKlWtJJA046y4mH8K5Fos1fQMQffywViruCXxD6MLZr5hUwLTjRnR/vQUAC0LuiYHCf9w/FK/xJR7dF4pQ61rDXRirtYgdH1mfPYXZvSRmM796li2ulw7P1zcTn/b0oI1d5x8lc4uzMvaP93Eea0TzF0cD6mT8QSGfc0f8e0Zu9Oku/FVvo34T1idb4eI0nReroFqBE07CmNiFe7v1ccZnAb3dvlbwpU2w4c/nljPtYIMzEX/68kojbZ0AbUefuKigKavRlG4cQlGQegIx2taATcp6Wd3Uplt6hy4TCwAvUyHs4NcoQNJ/d6kQxSX9W/WIo2eSGIsh/xU1064u6M0DybA6VG1vtuGyfXLZLSvSPyXtXeXpVQwxHf+JzGS0wrcv49sQXrmI/hsm/8Zxc310us0Svg5l8ukZQcPKodmXdjeIeXa1/e181E4eT9m9cLrxZDl02xrhXVgCXsmu8O6iYJUZ7/UwbOqnrrRW7jYQcgOzz+i/ADMBxL3hDb9L1J11x8mbXQRyL3CeKPokjkIwqQ18I18FqqnUv8+yhEs51cV7l5r1IP3YnUnUSu2oFbhvj3AFql05aOqVa0cnMnnWVRiEdsu+QAm/7TmovYqzxwlbj+APts1kld7DXo92y6dVoZEN9jI=
    username: AgBP3mPAJO/Xt2u8jBavDTC56ZZJB7uXceUI2/ULAnUFVlG6xlPePIR3PLCEnYErVluGHqinxXwS99eWyRmms5X6haeo0JiA7GeQ2bDFQBwQtIf3HN0ZhopgjU5eDQGAlxHFPShoJvVM04gEzHNXw3jqOiRxbnSqCFTFByKB3NlfGeTwbs4VYpnYDlkpXjSMx8xszOaV/bT4H7/u0O4twurpRIy1uoEeyVDCr3sdj6p/2g0W1GMRYMSCar8Y5brhG8qOk98PS9okVrRFMprNoqS0QYhOPIJwd3RsVc/txy1Y2MEsh+MnG+PPX9VObFcVGBd1J0sTMiYDG0IGIuLS8Lt+Lign0Jb82p8PHEKrwt6Xx47tLP/Pl1Xesi8ogS/HAjatDVwtWp0DCD8EWunNjr6TgrPoXSxZGRrIegyC0xlT3lnjJsvxiSFau859lcZXB5Hh8C5YJTSTh94INPqrxm/UTPGNxpiqT7SCP7Nsh1KbVrp2QxQCvuwGXTO57ZVv9fBUCqk0PxclHVNXuAFhKf+0vPOB2Hqqg0SB4CaeUvnjCHw40FPIybbds7+yXDRS6FQu680nGNLuc05P9z0IklmUe+qTl5cHQfrMjQAGlZOdqVjjJ2VMnImjDbffJZBa+NWhKuKkvT4aosr/lzIcRnIx2gFqgHqqyvY3zwzpaGB2035C7xWickDgnijsesvWwDi9nvt4CRa6thw=
  template:
    metadata:
      name: wazuh-api-cred
      namespace: wazuh
