---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-cluster-key
  namespace: wazuh
spec:
  encryptedData:
    key: AgBi3bHLxHbjLVZAEj86HAwTNFr0MAwE2HT3GEdGZf+eaPQ/C2koy3QhuYZi37fLXmcuxx/Oh7Xi678ukOXgKM+T/rG76El3FWyz8FqfvjQ3PMS/X6n5NyomolWWZ9infukXB8A9J/EMoOLtt2+d9gGSeJj3ibeAQENSaq6VZhEHQe7jaWOTduo8ugfbPkMNero7ohm93RfSXYPmVYlvfjRcKBk8x6oK/AdUi7mRF4RXPgJt+41+tNqLp66BAszlBJvcK/q0iQKnuPeSlQ0MgEcNDC2e2mhgOC/ozo2KjLLaCL+t99yGFPQ+IaKl89v9mKcEk+7K6qUQzb40ly3NAZDvrNw6WjkbVQ/JfzFhxKUJFRzN61a8G7Y37LnU/BKycrf9di/lgV9nz5jtwdK3DiCpc1cVfHcgd9Un/ZpgSOdN9ztnvmoXTh1ugaNlsp8Lv9G9VHsmZ+UfevvQShZQECKgCGG3CEufBLHJ13DG4zDvcCoifbp+9oWvx84reyqkPpmpyhYIzClMb/UZMf9+5GLDN7UyfiEe9w/P5mgz7VKmE1k0TRL+f7CPNNLZlydFSuvqKFBiK8aYMR/Z88YynJ4WzM0JpHTShmuDa3UIcovblYDFX8vjV/3Z9Eii7MSl9BJ6YZfl7f96ejdULiNTWOFbmjV7IGD7lM5SVGB7KHJZu3uL8pDqz/EvJ0obaWY+y1e63WyzydY8W4BQ+BElm4Q1gbsVQdYO1aQ5iqMoTZBF6R8TLc4Y3HGBMNvHzStMV4EZri3SnW7IXgWm3xIIX0+i
  template:
    metadata:
      name: wazuh-cluster-key
      namespace: wazuh
