apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-values
  namespace: wazuh
data:
  values.yaml: |-
    indexer:
      replicas: 1
      storage:
        storageClassName: default   # Use your AKS default storage class or change to managed-premium / managed-standard
        size: 50Gi

    manager:
      storage:
        storageClassName: default
        size: 20Gi
      service:
        type: ClusterIP

    dashboard:
      service:
        type: ClusterIP
      resources:
        requests:
          memory: "4Gi"
          cpu: "1000m"
        limits:
          memory: "8Gi"
          cpu: "2000m"
