apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - opensearch.yaml
  - backend.yaml
  - frontend.yaml
  - orborus.yaml
  - secrets/sealed
