apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shuffle-orborus
  namespace: shuffle
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shuffle-orborus
  namespace: shuffle
subjects:
  - kind: ServiceAccount
    name: shuffle-orborus
    namespace: shuffle
roleRef:
  kind: Role
  name: shuffle-orborus
  apiGroup: rbac.authorization.k8s.io
