apiVersion: v1
kind: Service
metadata:
  name: wazuh
  namespace: wazuh
  annotations: null
spec:
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: wazuh
  annotations: null
spec:
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: indexer
  namespace: wazuh
  annotations: null
spec:
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: wazuh
  annotations: null
spec:
  type: ClusterIP
