$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
  namespace: wazuh
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-cluster-key
  namespace: wazuh
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-cred
  namespace: wazuh
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: indexer-cred
  namespace: wazuh
